run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - gocognit
  - goconst
  - gocyclo
  - godot
  - gofmt
  - goimports
  - golint
  - goprintffuncname
  - gosec
  - govet
  - lll
  - misspell
  - nakedret
  - staticcheck
  - unconvert
  - unparam
  - whitespace
  - wsl

linters-settings:
  misspell:
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  govet:
    exclude:

issues:
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  exclude-rules:
  - path: pkg/xds/register.go
    linters:
    - godot
    - golint

