# permissions for end users to edit clusterloadassignments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterloadassignment-editor-role
rules:
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - clusterloadassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - clusterloadassignments/status
  verbs:
  - get
