# permissions for end users to view listeners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: listener-viewer-role
rules:
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - listeners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - listeners/status
  verbs:
  - get
