
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - listeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - listeners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - routeconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - routeconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - runtimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - runtimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - scopedrouteconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - scopedrouteconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - virtualhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - virtualhosts/status
  verbs:
  - get
  - patch
  - update
