# permissions for end users to view routeconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routeconfiguration-viewer-role
rules:
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - routeconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - routeconfigurations/status
  verbs:
  - get
