# permissions for end users to edit routeconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routeconfiguration-editor-role
rules:
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - routeconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - routeconfigurations/status
  verbs:
  - get
