# permissions for end users to edit scopedrouteconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scopedrouteconfiguration-editor-role
rules:
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - scopedrouteconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - envoy.projectcontour.io
  resources:
  - scopedrouteconfigurations/status
  verbs:
  - get
